# Generated by Django 2.2 on 2021-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dish_type', models.CharField(choices=[('Starters', 'Starters'), ('Main Course', 'Main Course'), ('Fried Rice and Noodles', 'Fried Rice and Noodles'), ('Bread', 'Bread'), ('Rolls', 'Rolls'), ('Momos', 'Momos'), ('Soups', 'Soups'), ('Others', 'Others')], max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('img', models.CharField(max_length=300)),
            ],
        ),
    ]
