# Generated by Django 2.2 on 2021-03-04 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreapp', '0004_reservation_occasion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('dishes_ordered', models.TextField()),
                ('dishes_total', models.PositiveIntegerField()),
                ('delivery_charge', models.PositiveIntegerField()),
                ('delivery_address', models.TextField()),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ("On It's Way", "On It's Way"), ('Cancelled', 'Cancelled')], default="On It's Way", max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
