# Generated by Django 2.2 on 2021-03-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_dish_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysSpecials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes', models.ManyToManyField(to='coreapp.Dish')),
            ],
        ),
    ]
